"""Independent application authentication for the remote operations console.

Credentials live only in macOS Keychain under the dedicated service
``hermes-orchestrator-remote`` and are never shared with, or derived from, any
existing orchestrator credential. No secret value is ever logged, printed, or
embedded in an exception; the application token is displayed exactly once by
the ``remote-auth-init`` command.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import secrets
from base64 import urlsafe_b64decode, urlsafe_b64encode
from collections import deque
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from typing import Protocol

from hermes_orchestrator.keychain import (
    KeychainItemExists,
    KeychainItemMissing,
    KeychainReadError,
)

REMOTE_SERVICE = "hermes-orchestrator-remote"
TOKEN_ACCOUNT = "token"
SIGNING_ACCOUNT = "session-signing"
SESSION_COOKIE_NAME = "hermes_remote_session"
SESSION_LIFETIME = timedelta(seconds=900)
LOGIN_FAILURE_LIMIT = 5
LOGIN_FAILURE_WINDOW = timedelta(minutes=15)

_CSRF_DOMAIN = b"hermes-remote-csrf"


class RemoteAuthError(Exception):
    """Base for remote authentication failures; messages carry no secrets."""


class CredentialExists(RemoteAuthError):
    """Initialization refused because a remote credential already exists."""


class CredentialConflict(RemoteAuthError):
    """A pre-existing token without provenance blocks initialization."""


class CredentialStateUnreadable(RemoteAuthError):
    """Keychain state could not be read reliably; nothing was created."""


class SessionInvalid(RemoteAuthError):
    """A cookie failed signature, structure, or client-binding checks."""


class SessionExpired(RemoteAuthError):
    """A structurally valid session is past its expiry."""


class SessionRevoked(RemoteAuthError):
    """A structurally valid session has been revoked."""


class RateLimited(RemoteAuthError):
    """Too many failed login attempts inside the sliding window."""


class SecretStore(Protocol):
    """The keychain surface the services need; tests inject in-memory fakes."""

    def read(self, service: str, account: str) -> str: ...

    def read_classified(self, service: str, account: str) -> str: ...

    def create(self, service: str, account: str, secret: str) -> None: ...


def _b64encode(raw: bytes) -> str:
    return urlsafe_b64encode(raw).decode().rstrip("=")


def _b64decode(encoded: str) -> bytes:
    return urlsafe_b64decode((encoded + "=" * (-len(encoded) % 4)).encode())


def _utc_now() -> datetime:
    return datetime.now(UTC)


class RemoteCredentialService:
    """One-time initialization and constant-time verification of the token."""

    def __init__(self, *, keychain: SecretStore) -> None:
        self._keychain = keychain

    def initialize(self) -> str:
        """Create both credentials as one retryable outcome, never disclosing.

        Existing items are never overwritten or deleted, and only the token
        generated by this attempt is ever returned. Both accounts are
        classified before anything is written: an unreadable state fails
        closed with no create attempted, and a token without a signing secret
        is rejected — signing-first ordering means our own attempts cannot
        produce that state, so it carries no provenance and must never be
        redisplayed. Fresh attempts write the signing secret before the token
        so an interruption can never strand an undisplayed token.
        """

        token_present = self._present(TOKEN_ACCOUNT)
        signing_present = self._present(SIGNING_ACCOUNT)
        if token_present and signing_present:
            raise CredentialExists("remote credential already initialized")
        if token_present:
            raise CredentialConflict(
                "unproven token-only credential state; "
                "refusing to display or modify it"
            )
        self._ensure_signing_secret()
        token = secrets.token_urlsafe(32)
        try:
            self._keychain.create(REMOTE_SERVICE, TOKEN_ACCOUNT, token)
        except KeychainItemExists as error:
            raise CredentialExists("remote credential already initialized") from error
        return token

    def account_presence(self) -> dict[str, str]:
        """Classify each account as present, missing, or unknown; never values.

        Only a proven absence reads as ``missing``; any other read failure is
        ``unknown`` so diagnostics never invite retries over unreadable state.
        """

        states: dict[str, str] = {}
        for account in (TOKEN_ACCOUNT, SIGNING_ACCOUNT):
            try:
                self._keychain.read_classified(REMOTE_SERVICE, account)
            except KeychainItemMissing:
                states[account] = "missing"
            except Exception:
                states[account] = "unknown"
            else:
                states[account] = "present"
        return states

    def _ensure_signing_secret(self) -> None:
        # A pre-existing or concurrently written signing secret serves, but
        # only once a successful read proves the raced item usable.
        try:
            self._keychain.create(
                REMOTE_SERVICE, SIGNING_ACCOUNT, secrets.token_urlsafe(32)
            )
        except KeychainItemExists as error:
            try:
                self._keychain.read_classified(REMOTE_SERVICE, SIGNING_ACCOUNT)
            except Exception:
                raise CredentialStateUnreadable(
                    "keychain state could not be read reliably"
                ) from error

    def _present(self, account: str) -> bool:
        """True only for a proven readable item, False only for proven absence."""

        try:
            self._keychain.read_classified(REMOTE_SERVICE, account)
        except KeychainItemMissing:
            return False
        except KeychainReadError as error:
            raise CredentialStateUnreadable(
                "keychain state could not be read reliably"
            ) from error
        return True

    def verify(self, token: str) -> bool:
        """Compare against the stored token in constant time."""

        try:
            stored = self._keychain.read(REMOTE_SERVICE, TOKEN_ACCOUNT)
        except Exception:
            return False
        return hmac.compare_digest(stored.encode(), token.encode())


@dataclass(frozen=True)
class SessionCookie:
    """A hardened session cookie; the value never appears in reprs."""

    value: str = field(repr=False)
    name: str = SESSION_COOKIE_NAME
    http_only: bool = True
    secure: bool = True
    same_site: str = "Strict"
    path: str = "/"
    max_age: int = int(SESSION_LIFETIME.total_seconds())

    def header_value(self) -> str:
        return (
            f"{self.name}={self.value}; HttpOnly; Secure; "
            f"SameSite={self.same_site}; Path={self.path}; Max-Age={self.max_age}"
        )


@dataclass(frozen=True)
class SessionClaims:
    """Verified claims for one authenticated session."""

    session_id: str
    issued_at: datetime
    expires_at: datetime
    fingerprint: str

    @property
    def authenticated(self) -> bool:
        return True


class RevocationStore(Protocol):
    """Where revoked session ids are remembered."""

    def revoke(self, session_id: str) -> None: ...

    def is_revoked(self, session_id: str) -> bool: ...


class InMemoryRevocations:
    """Process-local revocation store; a durable backend can replace it."""

    def __init__(self) -> None:
        self._revoked: set[str] = set()

    def revoke(self, session_id: str) -> None:
        self._revoked.add(session_id)

    def is_revoked(self, session_id: str) -> bool:
        return session_id in self._revoked


class SessionService:
    """HMAC-SHA256-signed compact JSON session claims bound to one client."""

    def __init__(
        self,
        *,
        keychain: SecretStore,
        now: Callable[[], datetime] = _utc_now,
        revocations: RevocationStore | None = None,
    ) -> None:
        self._keychain = keychain
        self._now = now
        self._revocations = (
            revocations if revocations is not None else InMemoryRevocations()
        )

    def _signing_key(self) -> bytes:
        return self._keychain.read(REMOTE_SERVICE, SIGNING_ACCOUNT).encode()

    def create(self, client_fingerprint: str) -> SessionCookie:
        issued_at = self._now()
        claims = {
            "expires_at": (issued_at + SESSION_LIFETIME).isoformat(),
            "fingerprint": hashlib.sha256(client_fingerprint.encode()).hexdigest(),
            "issued_at": issued_at.isoformat(),
            "session_id": secrets.token_urlsafe(16),
        }
        payload = json.dumps(claims, sort_keys=True, separators=(",", ":")).encode()
        signature = hmac.digest(self._signing_key(), payload, "sha256")
        return SessionCookie(value=f"{_b64encode(payload)}.{_b64encode(signature)}")

    def verify(self, cookie: str, client_fingerprint: str) -> SessionClaims:
        payload, signature = self._parse(cookie)
        expected = hmac.digest(self._signing_key(), payload, "sha256")
        if not hmac.compare_digest(expected, signature):
            raise SessionInvalid("session signature mismatch")
        claims = self._claims(payload)
        presented = hashlib.sha256(client_fingerprint.encode()).hexdigest()
        if not hmac.compare_digest(
            claims.fingerprint.encode(), presented.encode()
        ):
            raise SessionInvalid("session client mismatch")
        if self._revocations.is_revoked(claims.session_id):
            raise SessionRevoked("session revoked")
        if self._now() >= claims.expires_at:
            raise SessionExpired("session expired")
        return claims

    def revoke(self, session_id: str) -> None:
        self._revocations.revoke(session_id)

    @staticmethod
    def _parse(cookie: str) -> tuple[bytes, bytes]:
        parts = cookie.split(".")
        if len(parts) != 2 or not parts[0] or not parts[1]:
            raise SessionInvalid("session cookie malformed")
        try:
            return _b64decode(parts[0]), _b64decode(parts[1])
        except (ValueError, UnicodeDecodeError) as error:
            raise SessionInvalid("session cookie malformed") from error

    @staticmethod
    def _claims(payload: bytes) -> SessionClaims:
        try:
            raw = json.loads(payload.decode())
            return SessionClaims(
                session_id=str(raw["session_id"]),
                issued_at=datetime.fromisoformat(raw["issued_at"]),
                expires_at=datetime.fromisoformat(raw["expires_at"]),
                fingerprint=str(raw["fingerprint"]),
            )
        except (ValueError, KeyError, TypeError, UnicodeDecodeError) as error:
            raise SessionInvalid("session claims malformed") from error


class CsrfService:
    """Per-session, per-form CSRF tokens bound to method and path."""

    def __init__(self, *, keychain: SecretStore) -> None:
        self._keychain = keychain

    def _csrf_key(self) -> bytes:
        signing = self._keychain.read(REMOTE_SERVICE, SIGNING_ACCOUNT).encode()
        return hmac.digest(signing, _CSRF_DOMAIN, "sha256")

    def _mac(self, session_id: str, method: str, path: str, nonce: str) -> str:
        message = "\x1f".join((session_id, method, path, nonce)).encode()
        return _b64encode(hmac.digest(self._csrf_key(), message, "sha256"))

    def issue(
        self, session_id: str, *, method: str = "POST", path: str = "/"
    ) -> str:
        nonce = secrets.token_urlsafe(16)
        return f"{nonce}.{self._mac(session_id, method, path, nonce)}"

    def verify(
        self,
        session_id: str,
        token: str,
        *,
        method: str = "POST",
        path: str = "/",
    ) -> bool:
        nonce, separator, mac = token.partition(".")
        if not nonce or not separator or not mac or "." in mac:
            return False
        expected = self._mac(session_id, method, path, nonce)
        return hmac.compare_digest(expected.encode(), mac.encode())


class LoginRateLimiter:
    """Sliding-window lockout: five failures per 15 minutes per client."""

    def __init__(
        self,
        *,
        now: Callable[[], datetime] = _utc_now,
        limit: int = LOGIN_FAILURE_LIMIT,
        window: timedelta = LOGIN_FAILURE_WINDOW,
    ) -> None:
        self._now = now
        self._limit = limit
        self._window = window
        self._failures: dict[tuple[str, str], deque[datetime]] = {}

    def _prune(self, key: tuple[str, str]) -> deque[datetime]:
        bucket = self._failures.setdefault(key, deque())
        threshold = self._now() - self._window
        while bucket and bucket[0] <= threshold:
            bucket.popleft()
        return bucket

    def check(self, address: str, fingerprint: str) -> None:
        """Raise RateLimited when the client is locked out."""

        if len(self._prune((address, fingerprint))) >= self._limit:
            raise RateLimited("too many failed login attempts")

    def record_failure(self, address: str, fingerprint: str) -> None:
        self._prune((address, fingerprint)).append(self._now())

    def record_success(self, address: str, fingerprint: str) -> None:
        self._failures.pop((address, fingerprint), None)
